//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ADCT.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ADCT_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDD_DLOption                    130
#define IDR_MENU1                       133
#define IDR_MENU2                       134
#define IDD_Login_Dialog                135
#define IDD_Order_Dialog                137
#define IDD_OptionLogin_Dlg             139
#define IDD_AutoTestOption_Dialog       141
#define IDC_Char_TB                     1001
#define IDC_NUM_TB                      1002
#define IDC_BUTTON1                     1003
#define IDC_BUTTON2                     1004
#define IDC_BUTTON3                     1005
#define IDC_ATOption_Btn                1005
#define IDC_ReadOption_Btn              1007
#define IDC_PortSet_CBB1                1009
#define IDC_PortOn_CB1                  1010
#define IDC_PortStatus_PG1              1011
#define IDC_PortStauts_TB1              1012
#define IDC_PortStatus_PG2              1013
#define IDC_PortStauts_TB2              1014
#define IDC_PortOn_CB2                  1015
#define IDC_PortSet_CBB2                1016
#define IDC_PortStatus_PG3              1017
#define IDC_PortStauts_TB3              1018
#define IDC_PortOn_CB3                  1019
#define IDC_PortSet_CBB3                1020
#define IDC_PortStatus_PG4              1021
#define IDC_PortStauts_TB4              1022
#define IDC_PortOn_CB4                  1023
#define IDC_PortSet_CBB4                1024
#define IDC_RICHEDIT21                  1025
#define IDC_LOG_RICHEDIT2               1025
#define IDC_RICHEDIT22                  1026
#define IDC_LOG_RICHEDIT1               1026
#define IDC_RICHEDIT23                  1027
#define IDC_LOG_RICHEDIT3               1027
#define IDC_RICHEDIT24                  1028
#define IDC_LOG_RICHEDIT4               1028
#define IDC_Refresh_Btn                 1029
#define IDC_Port_TB                     1030
#define IDC_Status_TB                   1031
#define IDC_DLOption_Btn                1032
#define IDC_stDAFileName_TB             1033
#define IDC_RootCert_File_DisplayEdit_TB 1034
#define IDC_stAuthFile_TB               1035
#define IDC_Certificate_File_DisplayEdit_TB 1036
#define IDC_stScatterFile_TB            1037
#define IDC_HWND_TB                     1038
#define IDC_MFCMENUBUTTON2              1042
#define IDC_UART_RD                     1043
#define IDC_USB_RD                      1044
#define IDC_UARTUSB_RD                  1045
#define IDC_Baud_CCB                    1046
#define IDC_DownloadType_CCB            1047
#define IDC_Auto_RD                     1048
#define IDC_Manual_RD                   1049
#define IDC_ResetToFactory_RD           1050
#define IDC_NAND_RD                     1052
#define IDC_NOR_RD                      1053
#define IDC_PORT1_LB                    1054
#define IDC_PORT2_LB                    1055
#define IDC_PORT3_LB                    1056
#define IDC_PORT4_LB                    1057
#define IDC_PortStart1_Btn              1058
#define IDC_PortStart2_Btn              1059
#define IDC_PortStart3_Btn              1060
#define IDC_PortStart4_Btn              1061
#define IDC_PortStop1_Btn               1062
#define IDC_PortStop2_Btn               1063
#define IDC_PortStop3_Btn               1064
#define IDC_PortStop4_Btn               1065
#define IDC_PortAllStart_Btn            1066
#define IDC_PortAllStop_Btn             1067
#define IDC_OrderName_CCB               1068
#define IDC_OrderStatic_LB              1069
#define IDC_BUTTON4                     1070
#define IDC_UserName_TB                 1071
#define IDC_Pwd_TB                      1072
#define IDC_ManagerName_TB              1073
#define IDC_ManagerPwd_TB               1074
#define IDC_VersionStatic_LB            1075
#define IDC_Version_TB                  1076
#define IDC_PowerComSelect_CCB          1076
#define IDC_RadioAddress_TB             1077
#define IDC_OrderDownload_PG            1078
#define IDC_Tips_LB1                    1080
#define IDC_Tips_LB2                    1081
#define IDC_Tips_LB3                    1083
#define IDC_SleepTimer_TB               1083
#define IDC_Tips_LB4                    1084
#define IDC_ATPortType                  1084
#define IDC_ATReTest_CK                 1085
#define IDC_ATTD_CK                     1086
#define IDC_ADCTInitStatus_LB           1087
#define ID_FILE_OPENDOWNLOADAGENTFILE   32862
#define ID_FILE_OPENAUTHENTICATIONFILE  32863
#define ID_FILE_SCATTERANDLOAD          32864
#define ID_FILE_OPENROOTCERTFILE        32865
#define ID_FILE_OPENCERTIFICATEFILE     32866
#define ID_FACTORYDATABASE_SETUPDATASOURCEFILE 32867
#define ID_FACTORYDATABASE_ENABLEFACTORYDATABASELOGGING 32868
#define ID_FACTORYDATABASE_SHOWFACTORYDATABASEFILE 32869
#define ID_BASEBANDCHIPOPTIONS_ENABLENFICS1 32870
#define ID_BASEBANDCHIPOPTIONS_BBCHIPVERSIONCHECK 32871
#define ID_BACKUPANDRESTORECALIBRATIONDATAOPTIONS_DOWNLOAD 32872
#define ID_BACKUPANDRESTORECALIBRATIONDATAOPTIONS_DOWNLOAD32877 32873
#define ID_BACKUPANDRESTORECALIBRATIONDATAOPTIONS_DOWNLOAD32878 32874
#define ID_BACKUPANDRESTORECALIBRATIONDATAOPTIONS_DOWNLOAD32879 32875
#define ID_BACKUPANDRESTORECALIBRATIONDATAOPTIONS_RESTORECALIBRATIONDATAONLY 32876
#define ID_BACKUPANDRESTORECALIBRATIONDATAOPTIONS_UPLOADUSERDATAONLY 32877
#define ID_BACKUPANDRESTORECALIBRATIONDATAOPTIONS_CHECKSDS 32878
#define ID_OPTIONS_SETBEGINCOMPORT      32879
#define ID_OPTIONS_USBDOWNLOADW         32880
#define ID_OPTIONS_USBDOWNLOAD          32881
#define ID_OPTIONS_USBDOWNLOAD32886     32882
#define ID_OPTIONS_ENABLEMMAA           32883
#define ID_OPTIONS_SENDROOTCERTFORCELY  32884
#define ID_OPTIONS_USBMETAMODEAFTERONESTATIONDOWNLOAD 32885
#define ID_OPTIONS_ENABLEUSB1           32886
#define ID_OPTIONS_DISABLELONG          32887
#define ID_OPTIONS_BACKUPNVRAMPARTITION 32888
#define ID_OPTIONS_ENTERMETAMODEAFTERDL 32889
#define ID_OPTIONS_SETTINGS             32890
#define ID_OPTIONS_NOR                  32891
#define ID_DEBUGLOGGING_ENABLEBROM      32892
#define ID_DEBUGLOGGING_CLEARBROM       32893
#define ID_DEBUGLOGGING_ENABLEMETA      32894
#define ID_DEBUGLOGGING_CLEARMETA       32895
#define ID_DEBUGLOGGING_ENABLEMDTLOGGING 32896
#define ID_DEBUGLOGGING_CLEARMDTLOG     32897
#define ID_DEBUGLOGGING_CLEARALLLOGS    32898
#define ID_DEBUGLOGGING_OPENDEVICEMANAGER 32899
#define ID_ENGINEER_SWITCHTOOPERATOR    32900
#define ID_ENGINEER_CHANGEPASSWORD      32901
#define ID_OPERATOR_SWITCHTOENGINEER    32902
#define ID_HELP_ABOUT                   32903
#define ID_OPTIONS_EXTERNALCLOCK        32904
#define ID_Menu                         32905
#define ID_OPTIONS_BASEBANDCHIPOPTIONS  32906
#define ID_OPTIONS_BACKUPANDRESTORECALIBRATIONDATAOPTIONS 32907
#define ID_IDENTIFY_ENGINEER            32908
#define ID_IDENTIFY_OPERATOR            32909

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32910
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
